
package com.vmware.pbm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:23.451+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "PbmDuplicateNameFault", targetNamespace = "urn:pbm")
public class PbmDuplicateNameFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.pbm.PbmDuplicateName pbmDuplicateNameFault;

    public PbmDuplicateNameFaultMsg() {
        super();
    }
    
    public PbmDuplicateNameFaultMsg(String message) {
        super(message);
    }
    
    public PbmDuplicateNameFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PbmDuplicateNameFaultMsg(String message, com.vmware.pbm.PbmDuplicateName pbmDuplicateNameFault) {
        super(message);
        this.pbmDuplicateNameFault = pbmDuplicateNameFault;
    }

    public PbmDuplicateNameFaultMsg(String message, com.vmware.pbm.PbmDuplicateName pbmDuplicateNameFault, Throwable cause) {
        super(message, cause);
        this.pbmDuplicateNameFault = pbmDuplicateNameFault;
    }

    public com.vmware.pbm.PbmDuplicateName getFaultInfo() {
        return this.pbmDuplicateNameFault;
    }
}
