
package com.vmware.pbm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:23.455+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "PbmFaultProfileStorageFaultFault", targetNamespace = "urn:pbm")
public class PbmFaultProfileStorageFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.pbm.PbmFaultProfileStorageFault pbmFaultProfileStorageFaultFault;

    public PbmFaultProfileStorageFaultFaultMsg() {
        super();
    }
    
    public PbmFaultProfileStorageFaultFaultMsg(String message) {
        super(message);
    }
    
    public PbmFaultProfileStorageFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PbmFaultProfileStorageFaultFaultMsg(String message, com.vmware.pbm.PbmFaultProfileStorageFault pbmFaultProfileStorageFaultFault) {
        super(message);
        this.pbmFaultProfileStorageFaultFault = pbmFaultProfileStorageFaultFault;
    }

    public PbmFaultProfileStorageFaultFaultMsg(String message, com.vmware.pbm.PbmFaultProfileStorageFault pbmFaultProfileStorageFaultFault, Throwable cause) {
        super(message, cause);
        this.pbmFaultProfileStorageFaultFault = pbmFaultProfileStorageFaultFault;
    }

    public com.vmware.pbm.PbmFaultProfileStorageFault getFaultInfo() {
        return this.pbmFaultProfileStorageFaultFault;
    }
}
