
package com.vmware.pbm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:23.467+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "PbmLegacyHubsNotSupportedFault", targetNamespace = "urn:pbm")
public class PbmLegacyHubsNotSupportedFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.pbm.PbmLegacyHubsNotSupported pbmLegacyHubsNotSupportedFault;

    public PbmLegacyHubsNotSupportedFaultMsg() {
        super();
    }
    
    public PbmLegacyHubsNotSupportedFaultMsg(String message) {
        super(message);
    }
    
    public PbmLegacyHubsNotSupportedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PbmLegacyHubsNotSupportedFaultMsg(String message, com.vmware.pbm.PbmLegacyHubsNotSupported pbmLegacyHubsNotSupportedFault) {
        super(message);
        this.pbmLegacyHubsNotSupportedFault = pbmLegacyHubsNotSupportedFault;
    }

    public PbmLegacyHubsNotSupportedFaultMsg(String message, com.vmware.pbm.PbmLegacyHubsNotSupported pbmLegacyHubsNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.pbmLegacyHubsNotSupportedFault = pbmLegacyHubsNotSupportedFault;
    }

    public com.vmware.pbm.PbmLegacyHubsNotSupported getFaultInfo() {
        return this.pbmLegacyHubsNotSupportedFault;
    }
}
