package com.vmware.pbm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:23.473+05:30
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:pbm", name = "PbmPortType")
@XmlSeeAlso({com.vmware.vim25.ObjectFactory.class, ObjectFactory.class})
public interface PbmPortType {

    @WebMethod(operationName = "PbmQueryProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryProfileRequestType")
    @ResponseWrapper(localName = "PbmQueryProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryProfileResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfileId> pbmQueryProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "resourceType", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileResourceType resourceType,
        @WebParam(name = "profileCategory", targetNamespace = "urn:pbm")
        java.lang.String profileCategory
    ) throws RuntimeFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmQueryMatchingHub", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryMatchingHub", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryMatchingHubRequestType")
    @ResponseWrapper(localName = "PbmQueryMatchingHubResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryMatchingHubResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmPlacementHub> pbmQueryMatchingHub(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hubsToSearch", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> hubsToSearch,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQueryAssociatedProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryAssociatedProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedProfileRequestType")
    @ResponseWrapper(localName = "PbmQueryAssociatedProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedProfileResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfileId> pbmQueryAssociatedProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entity", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmServerObjectRef entity
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFetchResourceType", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchResourceType", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchResourceTypeRequestType")
    @ResponseWrapper(localName = "PbmFetchResourceTypeResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchResourceTypeResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfileResourceType> pbmFetchResourceType(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmCreate", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCreate", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCreateRequestType")
    @ResponseWrapper(localName = "PbmCreateResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCreateResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public com.vmware.pbm.PbmProfileId pbmCreate(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "createSpec", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmCapabilityProfileCreateSpec createSpec
    ) throws RuntimeFaultFaultMsg, PbmDuplicateNameFaultMsg, PbmFaultProfileStorageFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmCheckCompliance", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCheckCompliance", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckComplianceRequestType")
    @ResponseWrapper(localName = "PbmCheckComplianceResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckComplianceResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmComplianceResult> pbmCheckCompliance(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entities", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entities,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmRetrieveContent", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmRetrieveContent", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmRetrieveContentRequestType")
    @ResponseWrapper(localName = "PbmRetrieveContentResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmRetrieveContentResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfile> pbmRetrieveContent(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profileIds", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmProfileId> profileIds
    ) throws RuntimeFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmQueryMatchingHubWithSpec", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryMatchingHubWithSpec", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryMatchingHubWithSpecRequestType")
    @ResponseWrapper(localName = "PbmQueryMatchingHubWithSpecResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryMatchingHubWithSpecResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmPlacementHub> pbmQueryMatchingHubWithSpec(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hubsToSearch", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> hubsToSearch,
        @WebParam(name = "createSpec", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmCapabilityProfileCreateSpec createSpec
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmRetrieveServiceContent", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmRetrieveServiceContent", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmRetrieveServiceContentRequestType")
    @ResponseWrapper(localName = "PbmRetrieveServiceContentResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmRetrieveServiceContentResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public com.vmware.pbm.PbmServiceInstanceContent pbmRetrieveServiceContent(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmDelete", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmDelete", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmDeleteRequestType")
    @ResponseWrapper(localName = "PbmDeleteResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmDeleteResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfileOperationOutcome> pbmDelete(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profileId", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmProfileId> profileId
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQueryDefaultRequirementProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryDefaultRequirementProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryDefaultRequirementProfileRequestType")
    @ResponseWrapper(localName = "PbmQueryDefaultRequirementProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryDefaultRequirementProfileResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public com.vmware.pbm.PbmProfileId pbmQueryDefaultRequirementProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hub", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmPlacementHub hub
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, PbmNonExistentHubsFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmQueryReplicationGroups", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryReplicationGroups", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryReplicationGroupsRequestType")
    @ResponseWrapper(localName = "PbmQueryReplicationGroupsResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryReplicationGroupsResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmQueryReplicationGroupResult> pbmQueryReplicationGroups(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entities", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entities
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmCheckCompatibility", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCheckCompatibility", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckCompatibilityRequestType")
    @ResponseWrapper(localName = "PbmCheckCompatibilityResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckCompatibilityResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmPlacementCompatibilityResult> pbmCheckCompatibility(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hubsToSearch", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> hubsToSearch,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmResetVSanDefaultProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmResetVSanDefaultProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmResetVSanDefaultProfileRequestType")
    @ResponseWrapper(localName = "PbmResetVSanDefaultProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmResetVSanDefaultProfileResponse")
    public void pbmResetVSanDefaultProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQueryByRollupComplianceStatus", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryByRollupComplianceStatus", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryByRollupComplianceStatusRequestType")
    @ResponseWrapper(localName = "PbmQueryByRollupComplianceStatusResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryByRollupComplianceStatusResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmServerObjectRef> pbmQueryByRollupComplianceStatus(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "status", targetNamespace = "urn:pbm")
        java.lang.String status
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmAssignDefaultRequirementProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmAssignDefaultRequirementProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmAssignDefaultRequirementProfileRequestType")
    @ResponseWrapper(localName = "PbmAssignDefaultRequirementProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmAssignDefaultRequirementProfileResponse")
    public void pbmAssignDefaultRequirementProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile,
        @WebParam(name = "datastores", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> datastores
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, PbmNonExistentHubsFaultMsg, InvalidArgumentFaultMsg, PbmLegacyHubsNotSupportedFaultMsg;

    @WebMethod(operationName = "PbmFetchRollupComplianceResult", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchRollupComplianceResult", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchRollupComplianceResultRequestType")
    @ResponseWrapper(localName = "PbmFetchRollupComplianceResultResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchRollupComplianceResultResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmRollupComplianceResult> pbmFetchRollupComplianceResult(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entity", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entity
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmCheckCompatibilityWithSpec", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCheckCompatibilityWithSpec", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckCompatibilityWithSpecRequestType")
    @ResponseWrapper(localName = "PbmCheckCompatibilityWithSpecResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckCompatibilityWithSpecResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmPlacementCompatibilityResult> pbmCheckCompatibilityWithSpec(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hubsToSearch", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> hubsToSearch,
        @WebParam(name = "profileSpec", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmCapabilityProfileCreateSpec profileSpec
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmUpdate", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmUpdate", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmUpdateRequestType")
    @ResponseWrapper(localName = "PbmUpdateResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmUpdateResponse")
    public void pbmUpdate(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profileId", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profileId,
        @WebParam(name = "updateSpec", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmCapabilityProfileUpdateSpec updateSpec
    ) throws RuntimeFaultFaultMsg, PbmFaultProfileStorageFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmQueryAssociatedProfiles", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryAssociatedProfiles", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedProfilesRequestType")
    @ResponseWrapper(localName = "PbmQueryAssociatedProfilesResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedProfilesResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmQueryProfileResult> pbmQueryAssociatedProfiles(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entities", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entities
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQuerySpaceStatsForStorageContainer", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQuerySpaceStatsForStorageContainer", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQuerySpaceStatsForStorageContainerRequestType")
    @ResponseWrapper(localName = "PbmQuerySpaceStatsForStorageContainerResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQuerySpaceStatsForStorageContainerResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmDatastoreSpaceStatistics> pbmQuerySpaceStatsForStorageContainer(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "datastore", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmServerObjectRef datastore,
        @WebParam(name = "capabilityProfileId", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmProfileId> capabilityProfileId
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, InvalidArgumentFaultMsg;

    @WebMethod(operationName = "PbmQueryAssociatedEntities", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryAssociatedEntities", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedEntitiesRequestType")
    @ResponseWrapper(localName = "PbmQueryAssociatedEntitiesResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedEntitiesResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmQueryProfileResult> pbmQueryAssociatedEntities(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profiles", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmProfileId> profiles
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQueryAssociatedEntity", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryAssociatedEntity", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedEntityRequestType")
    @ResponseWrapper(localName = "PbmQueryAssociatedEntityResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryAssociatedEntityResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmServerObjectRef> pbmQueryAssociatedEntity(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile,
        @WebParam(name = "entityType", targetNamespace = "urn:pbm")
        java.lang.String entityType
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFetchComplianceResult", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchComplianceResult", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchComplianceResultRequestType")
    @ResponseWrapper(localName = "PbmFetchComplianceResultResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchComplianceResultResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmComplianceResult> pbmFetchComplianceResult(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entities", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entities,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFetchVendorInfo", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchVendorInfo", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchVendorInfoRequestType")
    @ResponseWrapper(localName = "PbmFetchVendorInfoResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchVendorInfoResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmCapabilityVendorResourceTypeInfo> pbmFetchVendorInfo(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "resourceType", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileResourceType resourceType
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFetchCapabilitySchema", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchCapabilitySchema", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchCapabilitySchemaRequestType")
    @ResponseWrapper(localName = "PbmFetchCapabilitySchemaResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchCapabilitySchemaResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmCapabilitySchema> pbmFetchCapabilitySchema(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "vendorUuid", targetNamespace = "urn:pbm")
        java.lang.String vendorUuid,
        @WebParam(name = "lineOfService", targetNamespace = "urn:pbm")
        java.util.List<java.lang.String> lineOfService
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFetchCapabilityMetadata", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFetchCapabilityMetadata", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchCapabilityMetadataRequestType")
    @ResponseWrapper(localName = "PbmFetchCapabilityMetadataResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFetchCapabilityMetadataResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmCapabilityMetadataPerCategory> pbmFetchCapabilityMetadata(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "resourceType", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileResourceType resourceType,
        @WebParam(name = "vendorUuid", targetNamespace = "urn:pbm")
        java.lang.String vendorUuid
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmCheckRequirements", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCheckRequirements", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckRequirementsRequestType")
    @ResponseWrapper(localName = "PbmCheckRequirementsResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckRequirementsResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmPlacementCompatibilityResult> pbmCheckRequirements(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "hubsToSearch", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> hubsToSearch,
        @WebParam(name = "placementSubjectRef", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmServerObjectRef placementSubjectRef,
        @WebParam(name = "placementSubjectRequirement", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementRequirement> placementSubjectRequirement
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmResetDefaultRequirementProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmResetDefaultRequirementProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmResetDefaultRequirementProfileRequestType")
    @ResponseWrapper(localName = "PbmResetDefaultRequirementProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmResetDefaultRequirementProfileResponse")
    public void pbmResetDefaultRequirementProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "profile", targetNamespace = "urn:pbm")
        com.vmware.pbm.PbmProfileId profile
    ) throws RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmFindApplicableDefaultProfile", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmFindApplicableDefaultProfile", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFindApplicableDefaultProfileRequestType")
    @ResponseWrapper(localName = "PbmFindApplicableDefaultProfileResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmFindApplicableDefaultProfileResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmProfile> pbmFindApplicableDefaultProfile(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "datastores", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> datastores
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, PbmNonExistentHubsFaultMsg, InvalidArgumentFaultMsg, PbmLegacyHubsNotSupportedFaultMsg;

    @WebMethod(operationName = "PbmCheckRollupCompliance", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmCheckRollupCompliance", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckRollupComplianceRequestType")
    @ResponseWrapper(localName = "PbmCheckRollupComplianceResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmCheckRollupComplianceResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmRollupComplianceResult> pbmCheckRollupCompliance(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "entity", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmServerObjectRef> entity
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg;

    @WebMethod(operationName = "PbmQueryDefaultRequirementProfiles", action = "urn:pbm/6.5")
    @RequestWrapper(localName = "PbmQueryDefaultRequirementProfiles", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryDefaultRequirementProfilesRequestType")
    @ResponseWrapper(localName = "PbmQueryDefaultRequirementProfilesResponse", targetNamespace = "urn:pbm", className = "com.vmware.pbm.PbmQueryDefaultRequirementProfilesResponse")
    @WebResult(name = "returnval", targetNamespace = "urn:pbm")
    public java.util.List<com.vmware.pbm.PbmDefaultProfileInfo> pbmQueryDefaultRequirementProfiles(
        @WebParam(name = "_this", targetNamespace = "urn:pbm")
        com.vmware.vim25.ManagedObjectReference _this,
        @WebParam(name = "datastores", targetNamespace = "urn:pbm")
        java.util.List<com.vmware.pbm.PbmPlacementHub> datastores
    ) throws PbmFaultFaultMsg, RuntimeFaultFaultMsg, PbmNonExistentHubsFaultMsg, InvalidArgumentFaultMsg;
}
