
package com.vmware.pbm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:23.437+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "RuntimeFaultFault", targetNamespace = "urn:pbm")
public class RuntimeFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.RuntimeFault runtimeFaultFault;

    public RuntimeFaultFaultMsg() {
        super();
    }
    
    public RuntimeFaultFaultMsg(String message) {
        super(message);
    }
    
    public RuntimeFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault) {
        super(message);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault, Throwable cause) {
        super(message, cause);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public com.vmware.vim25.RuntimeFault getFaultInfo() {
        return this.runtimeFaultFault;
    }
}
