
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.098+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ActiveDirectoryFaultFault", targetNamespace = "urn:vim25")
public class ActiveDirectoryFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault;

    public ActiveDirectoryFaultFaultMsg() {
        super();
    }
    
    public ActiveDirectoryFaultFaultMsg(String message) {
        super(message);
    }
    
    public ActiveDirectoryFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ActiveDirectoryFaultFaultMsg(String message, com.vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault) {
        super(message);
        this.activeDirectoryFaultFault = activeDirectoryFaultFault;
    }

    public ActiveDirectoryFaultFaultMsg(String message, com.vmware.vim25.ActiveDirectoryFault activeDirectoryFaultFault, Throwable cause) {
        super(message, cause);
        this.activeDirectoryFaultFault = activeDirectoryFaultFault;
    }

    public com.vmware.vim25.ActiveDirectoryFault getFaultInfo() {
        return this.activeDirectoryFaultFault;
    }
}
