
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.011+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AlreadyUpgradedFault", targetNamespace = "urn:vim25")
public class AlreadyUpgradedFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.AlreadyUpgraded alreadyUpgradedFault;

    public AlreadyUpgradedFaultMsg() {
        super();
    }
    
    public AlreadyUpgradedFaultMsg(String message) {
        super(message);
    }
    
    public AlreadyUpgradedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyUpgradedFaultMsg(String message, com.vmware.vim25.AlreadyUpgraded alreadyUpgradedFault) {
        super(message);
        this.alreadyUpgradedFault = alreadyUpgradedFault;
    }

    public AlreadyUpgradedFaultMsg(String message, com.vmware.vim25.AlreadyUpgraded alreadyUpgradedFault, Throwable cause) {
        super(message, cause);
        this.alreadyUpgradedFault = alreadyUpgradedFault;
    }

    public com.vmware.vim25.AlreadyUpgraded getFaultInfo() {
        return this.alreadyUpgradedFault;
    }
}
