
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.005+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AlreadyExistsFault", targetNamespace = "urn:vim25")
public class AlreadyExistsFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.AlreadyExists alreadyExistsFault;

    public AlreadyExistsFaultMsg() {
        super();
    }
    
    public AlreadyExistsFaultMsg(String message) {
        super(message);
    }
    
    public AlreadyExistsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyExistsFaultMsg(String message, com.vmware.vim25.AlreadyExists alreadyExistsFault) {
        super(message);
        this.alreadyExistsFault = alreadyExistsFault;
    }

    public AlreadyExistsFaultMsg(String message, com.vmware.vim25.AlreadyExists alreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.alreadyExistsFault = alreadyExistsFault;
    }

    public com.vmware.vim25.AlreadyExists getFaultInfo() {
        return this.alreadyExistsFault;
    }
}
