
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.816+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "AuthMinimumAdminPermissionFault", targetNamespace = "urn:vim25")
public class AuthMinimumAdminPermissionFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault;

    public AuthMinimumAdminPermissionFaultMsg() {
        super();
    }
    
    public AuthMinimumAdminPermissionFaultMsg(String message) {
        super(message);
    }
    
    public AuthMinimumAdminPermissionFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, com.vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault) {
        super(message);
        this.authMinimumAdminPermissionFault = authMinimumAdminPermissionFault;
    }

    public AuthMinimumAdminPermissionFaultMsg(String message, com.vmware.vim25.AuthMinimumAdminPermission authMinimumAdminPermissionFault, Throwable cause) {
        super(message, cause);
        this.authMinimumAdminPermissionFault = authMinimumAdminPermissionFault;
    }

    public com.vmware.vim25.AuthMinimumAdminPermission getFaultInfo() {
        return this.authMinimumAdminPermissionFault;
    }
}
