
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.055+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "CannotAccessFileFault", targetNamespace = "urn:vim25")
public class CannotAccessFileFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.CannotAccessFile cannotAccessFileFault;

    public CannotAccessFileFaultMsg() {
        super();
    }
    
    public CannotAccessFileFaultMsg(String message) {
        super(message);
    }
    
    public CannotAccessFileFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CannotAccessFileFaultMsg(String message, com.vmware.vim25.CannotAccessFile cannotAccessFileFault) {
        super(message);
        this.cannotAccessFileFault = cannotAccessFileFault;
    }

    public CannotAccessFileFaultMsg(String message, com.vmware.vim25.CannotAccessFile cannotAccessFileFault, Throwable cause) {
        super(message, cause);
        this.cannotAccessFileFault = cannotAccessFileFault;
    }

    public com.vmware.vim25.CannotAccessFile getFaultInfo() {
        return this.cannotAccessFileFault;
    }
}
