
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.240+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "CannotCreateFileFault", targetNamespace = "urn:vim25")
public class CannotCreateFileFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.CannotCreateFile cannotCreateFileFault;

    public CannotCreateFileFaultMsg() {
        super();
    }
    
    public CannotCreateFileFaultMsg(String message) {
        super(message);
    }
    
    public CannotCreateFileFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CannotCreateFileFaultMsg(String message, com.vmware.vim25.CannotCreateFile cannotCreateFileFault) {
        super(message);
        this.cannotCreateFileFault = cannotCreateFileFault;
    }

    public CannotCreateFileFaultMsg(String message, com.vmware.vim25.CannotCreateFile cannotCreateFileFault, Throwable cause) {
        super(message, cause);
        this.cannotCreateFileFault = cannotCreateFileFault;
    }

    public com.vmware.vim25.CannotCreateFile getFaultInfo() {
        return this.cannotCreateFileFault;
    }
}
