
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.011+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ConcurrentAccessFault", targetNamespace = "urn:vim25")
public class ConcurrentAccessFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ConcurrentAccess concurrentAccessFault;

    public ConcurrentAccessFaultMsg() {
        super();
    }
    
    public ConcurrentAccessFaultMsg(String message) {
        super(message);
    }
    
    public ConcurrentAccessFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ConcurrentAccessFaultMsg(String message, com.vmware.vim25.ConcurrentAccess concurrentAccessFault) {
        super(message);
        this.concurrentAccessFault = concurrentAccessFault;
    }

    public ConcurrentAccessFaultMsg(String message, com.vmware.vim25.ConcurrentAccess concurrentAccessFault, Throwable cause) {
        super(message, cause);
        this.concurrentAccessFault = concurrentAccessFault;
    }

    public com.vmware.vim25.ConcurrentAccess getFaultInfo() {
        return this.concurrentAccessFault;
    }
}
