
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.980+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "CustomizationFaultFault", targetNamespace = "urn:vim25")
public class CustomizationFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.CustomizationFault customizationFaultFault;

    public CustomizationFaultFaultMsg() {
        super();
    }
    
    public CustomizationFaultFaultMsg(String message) {
        super(message);
    }
    
    public CustomizationFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public CustomizationFaultFaultMsg(String message, com.vmware.vim25.CustomizationFault customizationFaultFault) {
        super(message);
        this.customizationFaultFault = customizationFaultFault;
    }

    public CustomizationFaultFaultMsg(String message, com.vmware.vim25.CustomizationFault customizationFaultFault, Throwable cause) {
        super(message, cause);
        this.customizationFaultFault = customizationFaultFault;
    }

    public com.vmware.vim25.CustomizationFault getFaultInfo() {
        return this.customizationFaultFault;
    }
}
