
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.836+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "DuplicateNameFault", targetNamespace = "urn:vim25")
public class DuplicateNameFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.DuplicateName duplicateNameFault;

    public DuplicateNameFaultMsg() {
        super();
    }
    
    public DuplicateNameFaultMsg(String message) {
        super(message);
    }
    
    public DuplicateNameFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateNameFaultMsg(String message, com.vmware.vim25.DuplicateName duplicateNameFault) {
        super(message);
        this.duplicateNameFault = duplicateNameFault;
    }

    public DuplicateNameFaultMsg(String message, com.vmware.vim25.DuplicateName duplicateNameFault, Throwable cause) {
        super(message, cause);
        this.duplicateNameFault = duplicateNameFault;
    }

    public com.vmware.vim25.DuplicateName getFaultInfo() {
        return this.duplicateNameFault;
    }
}
