
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.966+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "DvsFaultFault", targetNamespace = "urn:vim25")
public class DvsFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.DvsFault dvsFaultFault;

    public DvsFaultFaultMsg() {
        super();
    }
    
    public DvsFaultFaultMsg(String message) {
        super(message);
    }
    
    public DvsFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DvsFaultFaultMsg(String message, com.vmware.vim25.DvsFault dvsFaultFault) {
        super(message);
        this.dvsFaultFault = dvsFaultFault;
    }

    public DvsFaultFaultMsg(String message, com.vmware.vim25.DvsFault dvsFaultFault, Throwable cause) {
        super(message, cause);
        this.dvsFaultFault = dvsFaultFault;
    }

    public com.vmware.vim25.DvsFault getFaultInfo() {
        return this.dvsFaultFault;
    }
}
