
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.047+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "DvsNotAuthorizedFault", targetNamespace = "urn:vim25")
public class DvsNotAuthorizedFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault;

    public DvsNotAuthorizedFaultMsg() {
        super();
    }
    
    public DvsNotAuthorizedFaultMsg(String message) {
        super(message);
    }
    
    public DvsNotAuthorizedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DvsNotAuthorizedFaultMsg(String message, com.vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault) {
        super(message);
        this.dvsNotAuthorizedFault = dvsNotAuthorizedFault;
    }

    public DvsNotAuthorizedFaultMsg(String message, com.vmware.vim25.DvsNotAuthorized dvsNotAuthorizedFault, Throwable cause) {
        super(message, cause);
        this.dvsNotAuthorizedFault = dvsNotAuthorizedFault;
    }

    public com.vmware.vim25.DvsNotAuthorized getFaultInfo() {
        return this.dvsNotAuthorizedFault;
    }
}
