
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.218+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "FileNotFoundFault", targetNamespace = "urn:vim25")
public class FileNotFoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.FileNotFound fileNotFoundFault;

    public FileNotFoundFaultMsg() {
        super();
    }
    
    public FileNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public FileNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public FileNotFoundFaultMsg(String message, com.vmware.vim25.FileNotFound fileNotFoundFault) {
        super(message);
        this.fileNotFoundFault = fileNotFoundFault;
    }

    public FileNotFoundFaultMsg(String message, com.vmware.vim25.FileNotFound fileNotFoundFault, Throwable cause) {
        super(message, cause);
        this.fileNotFoundFault = fileNotFoundFault;
    }

    public com.vmware.vim25.FileNotFound getFaultInfo() {
        return this.fileNotFoundFault;
    }
}
