
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.035+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "FileAlreadyExistsFault", targetNamespace = "urn:vim25")
public class FileAlreadyExistsFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.FileAlreadyExists fileAlreadyExistsFault;

    public FileAlreadyExistsFaultMsg() {
        super();
    }
    
    public FileAlreadyExistsFaultMsg(String message) {
        super(message);
    }
    
    public FileAlreadyExistsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public FileAlreadyExistsFaultMsg(String message, com.vmware.vim25.FileAlreadyExists fileAlreadyExistsFault) {
        super(message);
        this.fileAlreadyExistsFault = fileAlreadyExistsFault;
    }

    public FileAlreadyExistsFaultMsg(String message, com.vmware.vim25.FileAlreadyExists fileAlreadyExistsFault, Throwable cause) {
        super(message, cause);
        this.fileAlreadyExistsFault = fileAlreadyExistsFault;
    }

    public com.vmware.vim25.FileAlreadyExists getFaultInfo() {
        return this.fileAlreadyExistsFault;
    }
}
