
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.733+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "GuestOperationsFaultFault", targetNamespace = "urn:vim25")
public class GuestOperationsFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.GuestOperationsFault guestOperationsFaultFault;

    public GuestOperationsFaultFaultMsg() {
        super();
    }
    
    public GuestOperationsFaultFaultMsg(String message) {
        super(message);
    }
    
    public GuestOperationsFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public GuestOperationsFaultFaultMsg(String message, com.vmware.vim25.GuestOperationsFault guestOperationsFaultFault) {
        super(message);
        this.guestOperationsFaultFault = guestOperationsFaultFault;
    }

    public GuestOperationsFaultFaultMsg(String message, com.vmware.vim25.GuestOperationsFault guestOperationsFaultFault, Throwable cause) {
        super(message, cause);
        this.guestOperationsFaultFault = guestOperationsFaultFault;
    }

    public com.vmware.vim25.GuestOperationsFault getFaultInfo() {
        return this.guestOperationsFaultFault;
    }
}
