
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.040+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "HostConfigFailedFault", targetNamespace = "urn:vim25")
public class HostConfigFailedFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.HostConfigFailed hostConfigFailedFault;

    public HostConfigFailedFaultMsg() {
        super();
    }
    
    public HostConfigFailedFaultMsg(String message) {
        super(message);
    }
    
    public HostConfigFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostConfigFailedFaultMsg(String message, com.vmware.vim25.HostConfigFailed hostConfigFailedFault) {
        super(message);
        this.hostConfigFailedFault = hostConfigFailedFault;
    }

    public HostConfigFailedFaultMsg(String message, com.vmware.vim25.HostConfigFailed hostConfigFailedFault, Throwable cause) {
        super(message, cause);
        this.hostConfigFailedFault = hostConfigFailedFault;
    }

    public com.vmware.vim25.HostConfigFailed getFaultInfo() {
        return this.hostConfigFailedFault;
    }
}
