
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.974+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "HostConnectFaultFault", targetNamespace = "urn:vim25")
public class HostConnectFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.HostConnectFault hostConnectFaultFault;

    public HostConnectFaultFaultMsg() {
        super();
    }
    
    public HostConnectFaultFaultMsg(String message) {
        super(message);
    }
    
    public HostConnectFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public HostConnectFaultFaultMsg(String message, com.vmware.vim25.HostConnectFault hostConnectFaultFault) {
        super(message);
        this.hostConnectFaultFault = hostConnectFaultFault;
    }

    public HostConnectFaultFaultMsg(String message, com.vmware.vim25.HostConnectFault hostConnectFaultFault, Throwable cause) {
        super(message, cause);
        this.hostConnectFaultFault = hostConnectFaultFault;
    }

    public com.vmware.vim25.HostConnectFault getFaultInfo() {
        return this.hostConnectFaultFault;
    }
}
