
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.277+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "InaccessibleVFlashSourceFault", targetNamespace = "urn:vim25")
public class InaccessibleVFlashSourceFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InaccessibleVFlashSource inaccessibleVFlashSourceFault;

    public InaccessibleVFlashSourceFaultMsg() {
        super();
    }
    
    public InaccessibleVFlashSourceFaultMsg(String message) {
        super(message);
    }
    
    public InaccessibleVFlashSourceFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InaccessibleVFlashSourceFaultMsg(String message, com.vmware.vim25.InaccessibleVFlashSource inaccessibleVFlashSourceFault) {
        super(message);
        this.inaccessibleVFlashSourceFault = inaccessibleVFlashSourceFault;
    }

    public InaccessibleVFlashSourceFaultMsg(String message, com.vmware.vim25.InaccessibleVFlashSource inaccessibleVFlashSourceFault, Throwable cause) {
        super(message, cause);
        this.inaccessibleVFlashSourceFault = inaccessibleVFlashSourceFault;
    }

    public com.vmware.vim25.InaccessibleVFlashSource getFaultInfo() {
        return this.inaccessibleVFlashSourceFault;
    }
}
