
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.065+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidBundleFault", targetNamespace = "urn:vim25")
public class InvalidBundleFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidBundle invalidBundleFault;

    public InvalidBundleFaultMsg() {
        super();
    }
    
    public InvalidBundleFaultMsg(String message) {
        super(message);
    }
    
    public InvalidBundleFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidBundleFaultMsg(String message, com.vmware.vim25.InvalidBundle invalidBundleFault) {
        super(message);
        this.invalidBundleFault = invalidBundleFault;
    }

    public InvalidBundleFaultMsg(String message, com.vmware.vim25.InvalidBundle invalidBundleFault, Throwable cause) {
        super(message, cause);
        this.invalidBundleFault = invalidBundleFault;
    }

    public com.vmware.vim25.InvalidBundle getFaultInfo() {
        return this.invalidBundleFault;
    }
}
