
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.272+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidPrivilegeFault", targetNamespace = "urn:vim25")
public class InvalidPrivilegeFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidPrivilege invalidPrivilegeFault;

    public InvalidPrivilegeFaultMsg() {
        super();
    }
    
    public InvalidPrivilegeFaultMsg(String message) {
        super(message);
    }
    
    public InvalidPrivilegeFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPrivilegeFaultMsg(String message, com.vmware.vim25.InvalidPrivilege invalidPrivilegeFault) {
        super(message);
        this.invalidPrivilegeFault = invalidPrivilegeFault;
    }

    public InvalidPrivilegeFaultMsg(String message, com.vmware.vim25.InvalidPrivilege invalidPrivilegeFault, Throwable cause) {
        super(message, cause);
        this.invalidPrivilegeFault = invalidPrivilegeFault;
    }

    public com.vmware.vim25.InvalidPrivilege getFaultInfo() {
        return this.invalidPrivilegeFault;
    }
}
