
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.953+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidLoginFault", targetNamespace = "urn:vim25")
public class InvalidLoginFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidLogin invalidLoginFault;

    public InvalidLoginFaultMsg() {
        super();
    }
    
    public InvalidLoginFaultMsg(String message) {
        super(message);
    }
    
    public InvalidLoginFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLoginFaultMsg(String message, com.vmware.vim25.InvalidLogin invalidLoginFault) {
        super(message);
        this.invalidLoginFault = invalidLoginFault;
    }

    public InvalidLoginFaultMsg(String message, com.vmware.vim25.InvalidLogin invalidLoginFault, Throwable cause) {
        super(message, cause);
        this.invalidLoginFault = invalidLoginFault;
    }

    public com.vmware.vim25.InvalidLogin getFaultInfo() {
        return this.invalidLoginFault;
    }
}
