
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.977+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidPowerStateFault", targetNamespace = "urn:vim25")
public class InvalidPowerStateFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidPowerState invalidPowerStateFault;

    public InvalidPowerStateFaultMsg() {
        super();
    }
    
    public InvalidPowerStateFaultMsg(String message) {
        super(message);
    }
    
    public InvalidPowerStateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidPowerStateFaultMsg(String message, com.vmware.vim25.InvalidPowerState invalidPowerStateFault) {
        super(message);
        this.invalidPowerStateFault = invalidPowerStateFault;
    }

    public InvalidPowerStateFaultMsg(String message, com.vmware.vim25.InvalidPowerState invalidPowerStateFault, Throwable cause) {
        super(message, cause);
        this.invalidPowerStateFault = invalidPowerStateFault;
    }

    public com.vmware.vim25.InvalidPowerState getFaultInfo() {
        return this.invalidPowerStateFault;
    }
}
