
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.069+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidDatastorePathFault", targetNamespace = "urn:vim25")
public class InvalidDatastorePathFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidDatastorePath invalidDatastorePathFault;

    public InvalidDatastorePathFaultMsg() {
        super();
    }
    
    public InvalidDatastorePathFaultMsg(String message) {
        super(message);
    }
    
    public InvalidDatastorePathFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDatastorePathFaultMsg(String message, com.vmware.vim25.InvalidDatastorePath invalidDatastorePathFault) {
        super(message);
        this.invalidDatastorePathFault = invalidDatastorePathFault;
    }

    public InvalidDatastorePathFaultMsg(String message, com.vmware.vim25.InvalidDatastorePath invalidDatastorePathFault, Throwable cause) {
        super(message, cause);
        this.invalidDatastorePathFault = invalidDatastorePathFault;
    }

    public com.vmware.vim25.InvalidDatastorePath getFaultInfo() {
        return this.invalidDatastorePathFault;
    }
}
