
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.036+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidCollectorVersionFault", targetNamespace = "urn:vim25")
public class InvalidCollectorVersionFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidCollectorVersion invalidCollectorVersionFault;

    public InvalidCollectorVersionFaultMsg() {
        super();
    }
    
    public InvalidCollectorVersionFaultMsg(String message) {
        super(message);
    }
    
    public InvalidCollectorVersionFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCollectorVersionFaultMsg(String message, com.vmware.vim25.InvalidCollectorVersion invalidCollectorVersionFault) {
        super(message);
        this.invalidCollectorVersionFault = invalidCollectorVersionFault;
    }

    public InvalidCollectorVersionFaultMsg(String message, com.vmware.vim25.InvalidCollectorVersion invalidCollectorVersionFault, Throwable cause) {
        super(message, cause);
        this.invalidCollectorVersionFault = invalidCollectorVersionFault;
    }

    public com.vmware.vim25.InvalidCollectorVersion getFaultInfo() {
        return this.invalidCollectorVersionFault;
    }
}
