
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.261+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidFolderFault", targetNamespace = "urn:vim25")
public class InvalidFolderFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidFolder invalidFolderFault;

    public InvalidFolderFaultMsg() {
        super();
    }
    
    public InvalidFolderFaultMsg(String message) {
        super(message);
    }
    
    public InvalidFolderFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidFolderFaultMsg(String message, com.vmware.vim25.InvalidFolder invalidFolderFault) {
        super(message);
        this.invalidFolderFault = invalidFolderFault;
    }

    public InvalidFolderFaultMsg(String message, com.vmware.vim25.InvalidFolder invalidFolderFault, Throwable cause) {
        super(message, cause);
        this.invalidFolderFault = invalidFolderFault;
    }

    public com.vmware.vim25.InvalidFolder getFaultInfo() {
        return this.invalidFolderFault;
    }
}
