
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.054+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidDiskFormatFault", targetNamespace = "urn:vim25")
public class InvalidDiskFormatFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidDiskFormat invalidDiskFormatFault;

    public InvalidDiskFormatFaultMsg() {
        super();
    }
    
    public InvalidDiskFormatFaultMsg(String message) {
        super(message);
    }
    
    public InvalidDiskFormatFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidDiskFormatFaultMsg(String message, com.vmware.vim25.InvalidDiskFormat invalidDiskFormatFault) {
        super(message);
        this.invalidDiskFormatFault = invalidDiskFormatFault;
    }

    public InvalidDiskFormatFaultMsg(String message, com.vmware.vim25.InvalidDiskFormat invalidDiskFormatFault, Throwable cause) {
        super(message, cause);
        this.invalidDiskFormatFault = invalidDiskFormatFault;
    }

    public com.vmware.vim25.InvalidDiskFormat getFaultInfo() {
        return this.invalidDiskFormatFault;
    }
}
