
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.472+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidHostStateFault", targetNamespace = "urn:vim25")
public class InvalidHostStateFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidHostState invalidHostStateFault;

    public InvalidHostStateFaultMsg() {
        super();
    }
    
    public InvalidHostStateFaultMsg(String message) {
        super(message);
    }
    
    public InvalidHostStateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidHostStateFaultMsg(String message, com.vmware.vim25.InvalidHostState invalidHostStateFault) {
        super(message);
        this.invalidHostStateFault = invalidHostStateFault;
    }

    public InvalidHostStateFaultMsg(String message, com.vmware.vim25.InvalidHostState invalidHostStateFault, Throwable cause) {
        super(message, cause);
        this.invalidHostStateFault = invalidHostStateFault;
    }

    public com.vmware.vim25.InvalidHostState getFaultInfo() {
        return this.invalidHostStateFault;
    }
}
