
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.289+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "InvalidIpmiMacAddressFault", targetNamespace = "urn:vim25")
public class InvalidIpmiMacAddressFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.InvalidIpmiMacAddress invalidIpmiMacAddressFault;

    public InvalidIpmiMacAddressFaultMsg() {
        super();
    }
    
    public InvalidIpmiMacAddressFaultMsg(String message) {
        super(message);
    }
    
    public InvalidIpmiMacAddressFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidIpmiMacAddressFaultMsg(String message, com.vmware.vim25.InvalidIpmiMacAddress invalidIpmiMacAddressFault) {
        super(message);
        this.invalidIpmiMacAddressFault = invalidIpmiMacAddressFault;
    }

    public InvalidIpmiMacAddressFaultMsg(String message, com.vmware.vim25.InvalidIpmiMacAddress invalidIpmiMacAddressFault, Throwable cause) {
        super(message, cause);
        this.invalidIpmiMacAddressFault = invalidIpmiMacAddressFault;
    }

    public com.vmware.vim25.InvalidIpmiMacAddress getFaultInfo() {
        return this.invalidIpmiMacAddressFault;
    }
}
