
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.383+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultInvalidVnicFault", targetNamespace = "urn:vim25")
public class IscsiFaultInvalidVnicFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultInvalidVnic iscsiFaultInvalidVnicFault;

    public IscsiFaultInvalidVnicFaultMsg() {
        super();
    }
    
    public IscsiFaultInvalidVnicFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultInvalidVnicFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultInvalidVnicFaultMsg(String message, com.vmware.vim25.IscsiFaultInvalidVnic iscsiFaultInvalidVnicFault) {
        super(message);
        this.iscsiFaultInvalidVnicFault = iscsiFaultInvalidVnicFault;
    }

    public IscsiFaultInvalidVnicFaultMsg(String message, com.vmware.vim25.IscsiFaultInvalidVnic iscsiFaultInvalidVnicFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultInvalidVnicFault = iscsiFaultInvalidVnicFault;
    }

    public com.vmware.vim25.IscsiFaultInvalidVnic getFaultInfo() {
        return this.iscsiFaultInvalidVnicFault;
    }
}
