
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.387+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicHasNoUplinksFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicHasNoUplinksFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicHasNoUplinks iscsiFaultVnicHasNoUplinksFault;

    public IscsiFaultVnicHasNoUplinksFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicHasNoUplinksFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasNoUplinks iscsiFaultVnicHasNoUplinksFault) {
        super(message);
        this.iscsiFaultVnicHasNoUplinksFault = iscsiFaultVnicHasNoUplinksFault;
    }

    public IscsiFaultVnicHasNoUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasNoUplinks iscsiFaultVnicHasNoUplinksFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicHasNoUplinksFault = iscsiFaultVnicHasNoUplinksFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasNoUplinks getFaultInfo() {
        return this.iscsiFaultVnicHasNoUplinksFault;
    }
}
