
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.373+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicHasMultipleUplinksFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicHasMultipleUplinksFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks iscsiFaultVnicHasMultipleUplinksFault;

    public IscsiFaultVnicHasMultipleUplinksFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks iscsiFaultVnicHasMultipleUplinksFault) {
        super(message);
        this.iscsiFaultVnicHasMultipleUplinksFault = iscsiFaultVnicHasMultipleUplinksFault;
    }

    public IscsiFaultVnicHasMultipleUplinksFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks iscsiFaultVnicHasMultipleUplinksFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicHasMultipleUplinksFault = iscsiFaultVnicHasMultipleUplinksFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasMultipleUplinks getFaultInfo() {
        return this.iscsiFaultVnicHasMultipleUplinksFault;
    }
}
