
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.370+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicNotFoundFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicNotFoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicNotFound iscsiFaultVnicNotFoundFault;

    public IscsiFaultVnicNotFoundFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotFound iscsiFaultVnicNotFoundFault) {
        super(message);
        this.iscsiFaultVnicNotFoundFault = iscsiFaultVnicNotFoundFault;
    }

    public IscsiFaultVnicNotFoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotFound iscsiFaultVnicNotFoundFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicNotFoundFault = iscsiFaultVnicNotFoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicNotFound getFaultInfo() {
        return this.iscsiFaultVnicNotFoundFault;
    }
}
