
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.044+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicNotBoundFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicNotBoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicNotBound iscsiFaultVnicNotBoundFault;

    public IscsiFaultVnicNotBoundFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicNotBoundFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicNotBoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotBound iscsiFaultVnicNotBoundFault) {
        super(message);
        this.iscsiFaultVnicNotBoundFault = iscsiFaultVnicNotBoundFault;
    }

    public IscsiFaultVnicNotBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicNotBound iscsiFaultVnicNotBoundFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicNotBoundFault = iscsiFaultVnicNotBoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicNotBound getFaultInfo() {
        return this.iscsiFaultVnicNotBoundFault;
    }
}
