
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.393+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicAlreadyBoundFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicAlreadyBoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicAlreadyBound iscsiFaultVnicAlreadyBoundFault;

    public IscsiFaultVnicAlreadyBoundFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicAlreadyBoundFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicAlreadyBound iscsiFaultVnicAlreadyBoundFault) {
        super(message);
        this.iscsiFaultVnicAlreadyBoundFault = iscsiFaultVnicAlreadyBoundFault;
    }

    public IscsiFaultVnicAlreadyBoundFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicAlreadyBound iscsiFaultVnicAlreadyBoundFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicAlreadyBoundFault = iscsiFaultVnicAlreadyBoundFault;
    }

    public com.vmware.vim25.IscsiFaultVnicAlreadyBound getFaultInfo() {
        return this.iscsiFaultVnicAlreadyBoundFault;
    }
}
