
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.299+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicHasActivePathsFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicHasActivePathsFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicHasActivePaths iscsiFaultVnicHasActivePathsFault;

    public IscsiFaultVnicHasActivePathsFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicHasActivePathsFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicHasActivePathsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasActivePaths iscsiFaultVnicHasActivePathsFault) {
        super(message);
        this.iscsiFaultVnicHasActivePathsFault = iscsiFaultVnicHasActivePathsFault;
    }

    public IscsiFaultVnicHasActivePathsFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasActivePaths iscsiFaultVnicHasActivePathsFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicHasActivePathsFault = iscsiFaultVnicHasActivePathsFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasActivePaths getFaultInfo() {
        return this.iscsiFaultVnicHasActivePathsFault;
    }
}
