
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.058+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultVnicHasWrongUplinkFault", targetNamespace = "urn:vim25")
public class IscsiFaultVnicHasWrongUplinkFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFaultVnicHasWrongUplink iscsiFaultVnicHasWrongUplinkFault;

    public IscsiFaultVnicHasWrongUplinkFaultMsg() {
        super();
    }
    
    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasWrongUplink iscsiFaultVnicHasWrongUplinkFault) {
        super(message);
        this.iscsiFaultVnicHasWrongUplinkFault = iscsiFaultVnicHasWrongUplinkFault;
    }

    public IscsiFaultVnicHasWrongUplinkFaultMsg(String message, com.vmware.vim25.IscsiFaultVnicHasWrongUplink iscsiFaultVnicHasWrongUplinkFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultVnicHasWrongUplinkFault = iscsiFaultVnicHasWrongUplinkFault;
    }

    public com.vmware.vim25.IscsiFaultVnicHasWrongUplink getFaultInfo() {
        return this.iscsiFaultVnicHasWrongUplinkFault;
    }
}
