
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.019+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "IscsiFaultFault", targetNamespace = "urn:vim25")
public class IscsiFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.IscsiFault iscsiFaultFault;

    public IscsiFaultFaultMsg() {
        super();
    }
    
    public IscsiFaultFaultMsg(String message) {
        super(message);
    }
    
    public IscsiFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public IscsiFaultFaultMsg(String message, com.vmware.vim25.IscsiFault iscsiFaultFault) {
        super(message);
        this.iscsiFaultFault = iscsiFaultFault;
    }

    public IscsiFaultFaultMsg(String message, com.vmware.vim25.IscsiFault iscsiFaultFault, Throwable cause) {
        super(message, cause);
        this.iscsiFaultFault = iscsiFaultFault;
    }

    public com.vmware.vim25.IscsiFault getFaultInfo() {
        return this.iscsiFaultFault;
    }
}
