
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.351+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "LicenseServerUnavailableFault", targetNamespace = "urn:vim25")
public class LicenseServerUnavailableFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault;

    public LicenseServerUnavailableFaultMsg() {
        super();
    }
    
    public LicenseServerUnavailableFaultMsg(String message) {
        super(message);
    }
    
    public LicenseServerUnavailableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LicenseServerUnavailableFaultMsg(String message, com.vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault) {
        super(message);
        this.licenseServerUnavailableFault = licenseServerUnavailableFault;
    }

    public LicenseServerUnavailableFaultMsg(String message, com.vmware.vim25.LicenseServerUnavailable licenseServerUnavailableFault, Throwable cause) {
        super(message, cause);
        this.licenseServerUnavailableFault = licenseServerUnavailableFault;
    }

    public com.vmware.vim25.LicenseServerUnavailable getFaultInfo() {
        return this.licenseServerUnavailableFault;
    }
}
