
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.317+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "LimitExceededFault", targetNamespace = "urn:vim25")
public class LimitExceededFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.LimitExceeded limitExceededFault;

    public LimitExceededFaultMsg() {
        super();
    }
    
    public LimitExceededFaultMsg(String message) {
        super(message);
    }
    
    public LimitExceededFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public LimitExceededFaultMsg(String message, com.vmware.vim25.LimitExceeded limitExceededFault) {
        super(message);
        this.limitExceededFault = limitExceededFault;
    }

    public LimitExceededFaultMsg(String message, com.vmware.vim25.LimitExceeded limitExceededFault, Throwable cause) {
        super(message, cause);
        this.limitExceededFault = limitExceededFault;
    }

    public com.vmware.vim25.LimitExceeded getFaultInfo() {
        return this.limitExceededFault;
    }
}
