
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.026+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ManagedObjectNotFoundFault", targetNamespace = "urn:vim25")
public class ManagedObjectNotFoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ManagedObjectNotFound managedObjectNotFoundFault;

    public ManagedObjectNotFoundFaultMsg() {
        super();
    }
    
    public ManagedObjectNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public ManagedObjectNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ManagedObjectNotFoundFaultMsg(String message, com.vmware.vim25.ManagedObjectNotFound managedObjectNotFoundFault) {
        super(message);
        this.managedObjectNotFoundFault = managedObjectNotFoundFault;
    }

    public ManagedObjectNotFoundFaultMsg(String message, com.vmware.vim25.ManagedObjectNotFound managedObjectNotFoundFault, Throwable cause) {
        super(message, cause);
        this.managedObjectNotFoundFault = managedObjectNotFoundFault;
    }

    public com.vmware.vim25.ManagedObjectNotFound getFaultInfo() {
        return this.managedObjectNotFoundFault;
    }
}
