
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.032+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "MigrationFaultFault", targetNamespace = "urn:vim25")
public class MigrationFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.MigrationFault migrationFaultFault;

    public MigrationFaultFaultMsg() {
        super();
    }
    
    public MigrationFaultFaultMsg(String message) {
        super(message);
    }
    
    public MigrationFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public MigrationFaultFaultMsg(String message, com.vmware.vim25.MigrationFault migrationFaultFault) {
        super(message);
        this.migrationFaultFault = migrationFaultFault;
    }

    public MigrationFaultFaultMsg(String message, com.vmware.vim25.MigrationFault migrationFaultFault, Throwable cause) {
        super(message, cause);
        this.migrationFaultFault = migrationFaultFault;
    }

    public com.vmware.vim25.MigrationFault getFaultInfo() {
        return this.migrationFaultFault;
    }
}
