
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.064+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "MismatchedBundleFault", targetNamespace = "urn:vim25")
public class MismatchedBundleFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.MismatchedBundle mismatchedBundleFault;

    public MismatchedBundleFaultMsg() {
        super();
    }
    
    public MismatchedBundleFaultMsg(String message) {
        super(message);
    }
    
    public MismatchedBundleFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public MismatchedBundleFaultMsg(String message, com.vmware.vim25.MismatchedBundle mismatchedBundleFault) {
        super(message);
        this.mismatchedBundleFault = mismatchedBundleFault;
    }

    public MismatchedBundleFaultMsg(String message, com.vmware.vim25.MismatchedBundle mismatchedBundleFault, Throwable cause) {
        super(message, cause);
        this.mismatchedBundleFault = mismatchedBundleFault;
    }

    public com.vmware.vim25.MismatchedBundle getFaultInfo() {
        return this.mismatchedBundleFault;
    }
}
