
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.028+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "NoClientCertificateFault", targetNamespace = "urn:vim25")
public class NoClientCertificateFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.NoClientCertificate noClientCertificateFault;

    public NoClientCertificateFaultMsg() {
        super();
    }
    
    public NoClientCertificateFaultMsg(String message) {
        super(message);
    }
    
    public NoClientCertificateFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NoClientCertificateFaultMsg(String message, com.vmware.vim25.NoClientCertificate noClientCertificateFault) {
        super(message);
        this.noClientCertificateFault = noClientCertificateFault;
    }

    public NoClientCertificateFaultMsg(String message, com.vmware.vim25.NoClientCertificate noClientCertificateFault, Throwable cause) {
        super(message, cause);
        this.noClientCertificateFault = noClientCertificateFault;
    }

    public com.vmware.vim25.NoClientCertificate getFaultInfo() {
        return this.noClientCertificateFault;
    }
}
