
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.986+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "NoDiskSpaceFault", targetNamespace = "urn:vim25")
public class NoDiskSpaceFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.NoDiskSpace noDiskSpaceFault;

    public NoDiskSpaceFaultMsg() {
        super();
    }
    
    public NoDiskSpaceFaultMsg(String message) {
        super(message);
    }
    
    public NoDiskSpaceFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NoDiskSpaceFaultMsg(String message, com.vmware.vim25.NoDiskSpace noDiskSpaceFault) {
        super(message);
        this.noDiskSpaceFault = noDiskSpaceFault;
    }

    public NoDiskSpaceFaultMsg(String message, com.vmware.vim25.NoDiskSpace noDiskSpaceFault, Throwable cause) {
        super(message, cause);
        this.noDiskSpaceFault = noDiskSpaceFault;
    }

    public com.vmware.vim25.NoDiskSpace getFaultInfo() {
        return this.noDiskSpaceFault;
    }
}
