
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.957+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "NotFoundFault", targetNamespace = "urn:vim25")
public class NotFoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.NotFound notFoundFault;

    public NotFoundFaultMsg() {
        super();
    }
    
    public NotFoundFaultMsg(String message) {
        super(message);
    }
    
    public NotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFoundFaultMsg(String message, com.vmware.vim25.NotFound notFoundFault) {
        super(message);
        this.notFoundFault = notFoundFault;
    }

    public NotFoundFaultMsg(String message, com.vmware.vim25.NotFound notFoundFault, Throwable cause) {
        super(message, cause);
        this.notFoundFault = notFoundFault;
    }

    public com.vmware.vim25.NotFound getFaultInfo() {
        return this.notFoundFault;
    }
}
