
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.014+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "OutOfBoundsFault", targetNamespace = "urn:vim25")
public class OutOfBoundsFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.OutOfBounds outOfBoundsFault;

    public OutOfBoundsFaultMsg() {
        super();
    }
    
    public OutOfBoundsFaultMsg(String message) {
        super(message);
    }
    
    public OutOfBoundsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public OutOfBoundsFaultMsg(String message, com.vmware.vim25.OutOfBounds outOfBoundsFault) {
        super(message);
        this.outOfBoundsFault = outOfBoundsFault;
    }

    public OutOfBoundsFaultMsg(String message, com.vmware.vim25.OutOfBounds outOfBoundsFault, Throwable cause) {
        super(message, cause);
        this.outOfBoundsFault = outOfBoundsFault;
    }

    public com.vmware.vim25.OutOfBounds getFaultInfo() {
        return this.outOfBoundsFault;
    }
}
