
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.917+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "PatchMetadataInvalidFault", targetNamespace = "urn:vim25")
public class PatchMetadataInvalidFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault;

    public PatchMetadataInvalidFaultMsg() {
        super();
    }
    
    public PatchMetadataInvalidFaultMsg(String message) {
        super(message);
    }
    
    public PatchMetadataInvalidFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PatchMetadataInvalidFaultMsg(String message, com.vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault) {
        super(message);
        this.patchMetadataInvalidFault = patchMetadataInvalidFault;
    }

    public PatchMetadataInvalidFaultMsg(String message, com.vmware.vim25.PatchMetadataInvalid patchMetadataInvalidFault, Throwable cause) {
        super(message, cause);
        this.patchMetadataInvalidFault = patchMetadataInvalidFault;
    }

    public com.vmware.vim25.PatchMetadataInvalid getFaultInfo() {
        return this.patchMetadataInvalidFault;
    }
}
