
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.930+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "PlatformConfigFaultFault", targetNamespace = "urn:vim25")
public class PlatformConfigFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.PlatformConfigFault platformConfigFaultFault;

    public PlatformConfigFaultFaultMsg() {
        super();
    }
    
    public PlatformConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public PlatformConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public PlatformConfigFaultFaultMsg(String message, com.vmware.vim25.PlatformConfigFault platformConfigFaultFault) {
        super(message);
        this.platformConfigFaultFault = platformConfigFaultFault;
    }

    public PlatformConfigFaultFaultMsg(String message, com.vmware.vim25.PlatformConfigFault platformConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.platformConfigFaultFault = platformConfigFaultFault;
    }

    public com.vmware.vim25.PlatformConfigFault getFaultInfo() {
        return this.platformConfigFaultFault;
    }
}
