
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.233+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ProfileUpdateFailedFault", targetNamespace = "urn:vim25")
public class ProfileUpdateFailedFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault;

    public ProfileUpdateFailedFaultMsg() {
        super();
    }
    
    public ProfileUpdateFailedFaultMsg(String message) {
        super(message);
    }
    
    public ProfileUpdateFailedFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ProfileUpdateFailedFaultMsg(String message, com.vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault) {
        super(message);
        this.profileUpdateFailedFault = profileUpdateFailedFault;
    }

    public ProfileUpdateFailedFaultMsg(String message, com.vmware.vim25.ProfileUpdateFailed profileUpdateFailedFault, Throwable cause) {
        super(message, cause);
        this.profileUpdateFailedFault = profileUpdateFailedFault;
    }

    public com.vmware.vim25.ProfileUpdateFailed getFaultInfo() {
        return this.profileUpdateFailedFault;
    }
}
