
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.886+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ResourceInUseFault", targetNamespace = "urn:vim25")
public class ResourceInUseFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ResourceInUse resourceInUseFault;

    public ResourceInUseFaultMsg() {
        super();
    }
    
    public ResourceInUseFaultMsg(String message) {
        super(message);
    }
    
    public ResourceInUseFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceInUseFaultMsg(String message, com.vmware.vim25.ResourceInUse resourceInUseFault) {
        super(message);
        this.resourceInUseFault = resourceInUseFault;
    }

    public ResourceInUseFaultMsg(String message, com.vmware.vim25.ResourceInUse resourceInUseFault, Throwable cause) {
        super(message, cause);
        this.resourceInUseFault = resourceInUseFault;
    }

    public com.vmware.vim25.ResourceInUse getFaultInfo() {
        return this.resourceInUseFault;
    }
}
