
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.309+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ResourceNotAvailableFault", targetNamespace = "urn:vim25")
public class ResourceNotAvailableFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ResourceNotAvailable resourceNotAvailableFault;

    public ResourceNotAvailableFaultMsg() {
        super();
    }
    
    public ResourceNotAvailableFaultMsg(String message) {
        super(message);
    }
    
    public ResourceNotAvailableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ResourceNotAvailableFaultMsg(String message, com.vmware.vim25.ResourceNotAvailable resourceNotAvailableFault) {
        super(message);
        this.resourceNotAvailableFault = resourceNotAvailableFault;
    }

    public ResourceNotAvailableFaultMsg(String message, com.vmware.vim25.ResourceNotAvailable resourceNotAvailableFault, Throwable cause) {
        super(message, cause);
        this.resourceNotAvailableFault = resourceNotAvailableFault;
    }

    public com.vmware.vim25.ResourceNotAvailable getFaultInfo() {
        return this.resourceNotAvailableFault;
    }
}
