
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.423+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "RollbackFailureFault", targetNamespace = "urn:vim25")
public class RollbackFailureFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.RollbackFailure rollbackFailureFault;

    public RollbackFailureFaultMsg() {
        super();
    }
    
    public RollbackFailureFaultMsg(String message) {
        super(message);
    }
    
    public RollbackFailureFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RollbackFailureFaultMsg(String message, com.vmware.vim25.RollbackFailure rollbackFailureFault) {
        super(message);
        this.rollbackFailureFault = rollbackFailureFault;
    }

    public RollbackFailureFaultMsg(String message, com.vmware.vim25.RollbackFailure rollbackFailureFault, Throwable cause) {
        super(message, cause);
        this.rollbackFailureFault = rollbackFailureFault;
    }

    public com.vmware.vim25.RollbackFailure getFaultInfo() {
        return this.rollbackFailureFault;
    }
}
