
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.937+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "RuntimeFaultFault", targetNamespace = "urn:vim25")
public class RuntimeFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.RuntimeFault runtimeFaultFault;

    public RuntimeFaultFaultMsg() {
        super();
    }
    
    public RuntimeFaultFaultMsg(String message) {
        super(message);
    }
    
    public RuntimeFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault) {
        super(message);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public RuntimeFaultFaultMsg(String message, com.vmware.vim25.RuntimeFault runtimeFaultFault, Throwable cause) {
        super(message, cause);
        this.runtimeFaultFault = runtimeFaultFault;
    }

    public com.vmware.vim25.RuntimeFault getFaultInfo() {
        return this.runtimeFaultFault;
    }
}
