
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.979+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "SnapshotFaultFault", targetNamespace = "urn:vim25")
public class SnapshotFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.SnapshotFault snapshotFaultFault;

    public SnapshotFaultFaultMsg() {
        super();
    }
    
    public SnapshotFaultFaultMsg(String message) {
        super(message);
    }
    
    public SnapshotFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SnapshotFaultFaultMsg(String message, com.vmware.vim25.SnapshotFault snapshotFaultFault) {
        super(message);
        this.snapshotFaultFault = snapshotFaultFault;
    }

    public SnapshotFaultFaultMsg(String message, com.vmware.vim25.SnapshotFault snapshotFaultFault, Throwable cause) {
        super(message, cause);
        this.snapshotFaultFault = snapshotFaultFault;
    }

    public com.vmware.vim25.SnapshotFault getFaultInfo() {
        return this.snapshotFaultFault;
    }
}
