
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.754+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "TaskInProgressFault", targetNamespace = "urn:vim25")
public class TaskInProgressFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.TaskInProgress taskInProgressFault;

    public TaskInProgressFaultMsg() {
        super();
    }
    
    public TaskInProgressFaultMsg(String message) {
        super(message);
    }
    
    public TaskInProgressFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TaskInProgressFaultMsg(String message, com.vmware.vim25.TaskInProgress taskInProgressFault) {
        super(message);
        this.taskInProgressFault = taskInProgressFault;
    }

    public TaskInProgressFaultMsg(String message, com.vmware.vim25.TaskInProgress taskInProgressFault, Throwable cause) {
        super(message, cause);
        this.taskInProgressFault = taskInProgressFault;
    }

    public com.vmware.vim25.TaskInProgress getFaultInfo() {
        return this.taskInProgressFault;
    }
}
