
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:09.004+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "TimedoutFault", targetNamespace = "urn:vim25")
public class TimedoutFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.Timedout timedoutFault;

    public TimedoutFaultMsg() {
        super();
    }
    
    public TimedoutFaultMsg(String message) {
        super(message);
    }
    
    public TimedoutFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TimedoutFaultMsg(String message, com.vmware.vim25.Timedout timedoutFault) {
        super(message);
        this.timedoutFault = timedoutFault;
    }

    public TimedoutFaultMsg(String message, com.vmware.vim25.Timedout timedoutFault, Throwable cause) {
        super(message, cause);
        this.timedoutFault = timedoutFault;
    }

    public com.vmware.vim25.Timedout getFaultInfo() {
        return this.timedoutFault;
    }
}
