
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.653+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "ToolsUnavailableFault", targetNamespace = "urn:vim25")
public class ToolsUnavailableFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.ToolsUnavailable toolsUnavailableFault;

    public ToolsUnavailableFaultMsg() {
        super();
    }
    
    public ToolsUnavailableFaultMsg(String message) {
        super(message);
    }
    
    public ToolsUnavailableFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ToolsUnavailableFaultMsg(String message, com.vmware.vim25.ToolsUnavailable toolsUnavailableFault) {
        super(message);
        this.toolsUnavailableFault = toolsUnavailableFault;
    }

    public ToolsUnavailableFaultMsg(String message, com.vmware.vim25.ToolsUnavailable toolsUnavailableFault, Throwable cause) {
        super(message, cause);
        this.toolsUnavailableFault = toolsUnavailableFault;
    }

    public com.vmware.vim25.ToolsUnavailable getFaultInfo() {
        return this.toolsUnavailableFault;
    }
}
