
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.118+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "TooManyHostsFault", targetNamespace = "urn:vim25")
public class TooManyHostsFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.TooManyHosts tooManyHostsFault;

    public TooManyHostsFaultMsg() {
        super();
    }
    
    public TooManyHostsFaultMsg(String message) {
        super(message);
    }
    
    public TooManyHostsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public TooManyHostsFaultMsg(String message, com.vmware.vim25.TooManyHosts tooManyHostsFault) {
        super(message);
        this.tooManyHostsFault = tooManyHostsFault;
    }

    public TooManyHostsFaultMsg(String message, com.vmware.vim25.TooManyHosts tooManyHostsFault, Throwable cause) {
        super(message, cause);
        this.tooManyHostsFault = tooManyHostsFault;
    }

    public com.vmware.vim25.TooManyHosts getFaultInfo() {
        return this.tooManyHostsFault;
    }
}
