
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:06.724+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "UserNotFoundFault", targetNamespace = "urn:vim25")
public class UserNotFoundFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.UserNotFound userNotFoundFault;

    public UserNotFoundFaultMsg() {
        super();
    }
    
    public UserNotFoundFaultMsg(String message) {
        super(message);
    }
    
    public UserNotFoundFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public UserNotFoundFaultMsg(String message, com.vmware.vim25.UserNotFound userNotFoundFault) {
        super(message);
        this.userNotFoundFault = userNotFoundFault;
    }

    public UserNotFoundFaultMsg(String message, com.vmware.vim25.UserNotFound userNotFoundFault, Throwable cause) {
        super(message, cause);
        this.userNotFoundFault = userNotFoundFault;
    }

    public com.vmware.vim25.UserNotFound getFaultInfo() {
        return this.userNotFoundFault;
    }
}
