
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.114+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "VAppConfigFaultFault", targetNamespace = "urn:vim25")
public class VAppConfigFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.VAppConfigFault vAppConfigFaultFault;

    public VAppConfigFaultFaultMsg() {
        super();
    }
    
    public VAppConfigFaultFaultMsg(String message) {
        super(message);
    }
    
    public VAppConfigFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VAppConfigFaultFaultMsg(String message, com.vmware.vim25.VAppConfigFault vAppConfigFaultFault) {
        super(message);
        this.vAppConfigFaultFault = vAppConfigFaultFault;
    }

    public VAppConfigFaultFaultMsg(String message, com.vmware.vim25.VAppConfigFault vAppConfigFaultFault, Throwable cause) {
        super(message, cause);
        this.vAppConfigFaultFault = vAppConfigFaultFault;
    }

    public com.vmware.vim25.VAppConfigFault getFaultInfo() {
        return this.vAppConfigFaultFault;
    }
}
