
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.961+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "VimFaultFault", targetNamespace = "urn:vim25")
public class VimFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.VimFault vimFaultFault;

    public VimFaultFaultMsg() {
        super();
    }
    
    public VimFaultFaultMsg(String message) {
        super(message);
    }
    
    public VimFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VimFaultFaultMsg(String message, com.vmware.vim25.VimFault vimFaultFault) {
        super(message);
        this.vimFaultFault = vimFaultFault;
    }

    public VimFaultFaultMsg(String message, com.vmware.vim25.VimFault vimFaultFault, Throwable cause) {
        super(message, cause);
        this.vimFaultFault = vimFaultFault;
    }

    public com.vmware.vim25.VimFault getFaultInfo() {
        return this.vimFaultFault;
    }
}
