
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.995+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "VmFaultToleranceIssueFault", targetNamespace = "urn:vim25")
public class VmFaultToleranceIssueFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault;

    public VmFaultToleranceIssueFaultMsg() {
        super();
    }
    
    public VmFaultToleranceIssueFaultMsg(String message) {
        super(message);
    }
    
    public VmFaultToleranceIssueFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VmFaultToleranceIssueFaultMsg(String message, com.vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault) {
        super(message);
        this.vmFaultToleranceIssueFault = vmFaultToleranceIssueFault;
    }

    public VmFaultToleranceIssueFaultMsg(String message, com.vmware.vim25.VmFaultToleranceIssue vmFaultToleranceIssueFault, Throwable cause) {
        super(message, cause);
        this.vmFaultToleranceIssueFault = vmFaultToleranceIssueFault;
    }

    public com.vmware.vim25.VmFaultToleranceIssue getFaultInfo() {
        return this.vmFaultToleranceIssueFault;
    }
}
