
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-25T13:48:07.021+05:30
 * Generated source version: 3.1.6
 */

@WebFault(name = "VmfsAmbiguousMountFault", targetNamespace = "urn:vim25")
public class VmfsAmbiguousMountFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault;

    public VmfsAmbiguousMountFaultMsg() {
        super();
    }
    
    public VmfsAmbiguousMountFaultMsg(String message) {
        super(message);
    }
    
    public VmfsAmbiguousMountFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VmfsAmbiguousMountFaultMsg(String message, com.vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault) {
        super(message);
        this.vmfsAmbiguousMountFault = vmfsAmbiguousMountFault;
    }

    public VmfsAmbiguousMountFaultMsg(String message, com.vmware.vim25.VmfsAmbiguousMount vmfsAmbiguousMountFault, Throwable cause) {
        super(message, cause);
        this.vmfsAmbiguousMountFault = vmfsAmbiguousMountFault;
    }

    public com.vmware.vim25.VmfsAmbiguousMount getFaultInfo() {
        return this.vmfsAmbiguousMountFault;
    }
}
