
package com.vmware.vim25;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-18T20:02:08.997+03:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "VsanFaultFault", targetNamespace = "urn:vim25")
public class VsanFaultFaultMsg extends Exception {
    public static final long serialVersionUID = 1L;
    
    private com.vmware.vim25.VsanFault vsanFaultFault;

    public VsanFaultFaultMsg() {
        super();
    }
    
    public VsanFaultFaultMsg(String message) {
        super(message);
    }
    
    public VsanFaultFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public VsanFaultFaultMsg(String message, com.vmware.vim25.VsanFault vsanFaultFault) {
        super(message);
        this.vsanFaultFault = vsanFaultFault;
    }

    public VsanFaultFaultMsg(String message, com.vmware.vim25.VsanFault vsanFaultFault, Throwable cause) {
        super(message, cause);
        this.vsanFaultFault = vsanFaultFault;
    }

    public com.vmware.vim25.VsanFault getFaultInfo() {
        return this.vsanFaultFault;
    }
}
